// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  feature_highlight: dynamic(() => import("./FeatureHighlight")),
  hero: dynamic(() => import("./Hero")),
  product_grid: dynamic(() => import("./ProductGrid")),
};
